# FOR APACHE
# - name: Install Apache
#   hosts: target1
#   become: yes
#   tasks:
#     - name: Install apache package
#       apt:
#         name: apache2
#         state:  absent
#         update_cache: yes
#     - name: Start apache
#       service: 
#         name: apache2
#         state: started
# ---
# FOR NGINX
- name: Install nginx
  hosts: target1
  become: yes
  tasks:
    - name: copy nginx.list file
      ansible.builtin.copy:
        src: nginx.list
        dest: /etc/apt/sources.list.d/nginx.list
        owner: vagrant
        group: vagrant
        # mode: u=rw, g=r, o=r
    - name: signing with nginxx public key
      ansible.builtin.apt_key:
        url: https://nginx.org/keys/nginx_signing.key
        state: present
    - name: update apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #one day
    - name: install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
    - name: start nginx
      service:
        name: nginx
        state: started


